version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: roowpwd
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
    ports:
      - "9906:3306"
  web:
    build: ./
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "8001:80"
    stdin_open: true
    tty: true