version: '3'

services:
  db:
    image: mysql:latest
    command:
      - "--default-authentication-plugin=mysql_native_password"
    container_name: tsvm_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: tsvm
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
    ports:
      - "9906:3306"
  web:
    build: ./docker/
    container_name: tsvm_php_web
    depends_on:
      - db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "8001:80"
    links:
      - db
    stdin_open: true
    tty: true